# Generated by Django 5.2 on 2025-05-06 22:47

import django.db.models.deletion
import users.models.user_verification
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserVerfication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('expires_at', models.DateTimeField(default=users.models.user_verification.get_expire_date)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
